name = "foldy-friends"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".worker-next/index.mjs"
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "c983657806904d7c8e9131af35a6d09c"